language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=03990f10d1bc434a08af1af70b30627f5333955eb21bf21c3b45eade086b92b5
    - NODE_ENV=test
    - PGPASSWORD=
    - PGPORT=5433
    - PGUSER=postgres
    - PGHOST=localhost
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
  - psql -c 'create database testdb;' -U postgres
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
matrix:
  include:
  - node_js: '10'
  # - node_js: '12'
cache:
  directories: node_modules
deploy:
  provider: heroku
  api_key:
    secure: Ydsw8O7Hothfio25hXLxAPeP7j8XIfvCsC4lfVUiv2G3fhxQ6jH8kmr14ZITgHEghcR1GZGjQCY9H3MKWnLbolMGn6XYHaANrFcaLzjq8foCekWEW88Qp8qIwSsIFCAGu4gpjR8qM1tx6QOuQpKEQ8VOyaOp++2/TdsucyASygpuQqnkBe7LkRbqHm2IRpjrUaolmJDRykRWojHpJUbLjSwuWR7V04JbKsMcqvUTkuMiXDS/6lmH4ihDnKeRnD/jqgK8hayENxLyTCF+f1iYqBHt8QnjiURmcipxkYXiWWdwZ79uYwnY/HbW3hOEROQoyeOj8s3uOk/Bgd+Z2W4rn3baHitZlhSR+PBQPaksNci0nifmYwlqH2v2BdnlZ+FRshGQKBfMIeA93ATfVTrhqjX1g9doZ+mkVjP82HuX1Ei3LSt9g7Vuy6DIbc988haPqJAilFc32sXwYCgChEy/bc2gyaNMeZUBSJOH9PI3kFnuKyRVIUpsbr/1pGKGL+9oYA87cpvH0ze4fSRSzh8pZOPMv6EkbtmOOIItOqi7KdLPPkrRVh8YLRfqN2O3IQMun4mqGmO8VgC4CqUz2w6FmW2HtT5b/pIZOQx+oOKgKPUEtoVYWonx8oGA4nNqL/B2TUMsMmP/JBvzmOxeGQ3UTRK/OVKoTa5aPhYK4MALgvU=
  app: qcredit
  on: develop
after_success: yarn coverage
