language: node_js
matrix:
    include:
        - node_js: "10"
        - node_js: "12"
cache:
    directories: "node_modules"

# Generate and send coverage data to coveralls
after_script: yarn test-coveralls
