language: node_js
matrix:
    include:
        - node_js: "10"
        - node_js: "12"
cache:
    directories: "node_modules"

# Generate and send coverage report to coveralls
after_success: yarn coverage
